# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e08776ad53a502ca24433286851bb21960766796e7aeccd6a91d357e079c433dbaea7d5ea945ea13d99e806b46c1a684463ebdf9317586880b2e5ef2faa667a0

test:
  secret_key_base: 35c1cbc51199a0c061982cd7b99cfb54ede184ed171784af89cab06eff7e99db2074d47aa3bf9b04ffbf092350cf1bf52296febba446ec0a73585f54abea5446

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
